# Generated by Django 5.0.6 on 2024-08-23 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='variant',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='variant',
            name='product',
        ),
        migrations.AlterField(
            model_name='products',
            name='UpdatedDate',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='home.products')),
            ],
        ),
        migrations.CreateModel(
            name='VariantOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='home.productvariant')),
            ],
        ),
        migrations.DeleteModel(
            name='SubVariant',
        ),
        migrations.DeleteModel(
            name='Variant',
        ),
    ]
