# Generated by Django 5.0.6 on 2024-08-23 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_variant_unique_together_remove_variant_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variantoption',
            name='variant',
        ),
        migrations.DeleteModel(
            name='ProductVariant',
        ),
        migrations.DeleteModel(
            name='VariantOption',
        ),
    ]
